{
    "total_count": 333,
    "incomplete_results": false,
    "items": [
      {
        "login": "RABINA",
        "id": 10548116,
        "node_id": "MDQ6VXNlcjEwNTQ4MTE2",
        "avatar_url": "https://avatars.githubusercontent.com/u/10548116?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/RABINA",
        "html_url": "https://github.com/RABINA",
        "followers_url": "https://api.github.com/users/RABINA/followers",
        "following_url": "https://api.github.com/users/RABINA/following{/other_user}",
        "gists_url": "https://api.github.com/users/RABINA/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/RABINA/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/RABINA/subscriptions",
        "organizations_url": "https://api.github.com/users/RABINA/orgs",
        "repos_url": "https://api.github.com/users/RABINA/repos",
        "events_url": "https://api.github.com/users/RABINA/events{/privacy}",
        "received_events_url": "https://api.github.com/users/RABINA/received_events",
        "type": "User",
        "site_admin": false,
        "score": 1.0
      },